language: python
python:
  - '3.8'

install:
  - pip install flake8
  - pip install .

script:
  - flake8

before_deploy:
  - git describe --tags > VERSION

deploy:
  provider: pypi
  skip_cleanup: true
  user: nickw444-deploy
  password:
    secure: j4tpkUDxDHEY4X4SoNZCcj0fw51JgdqY4t5FkvyiirQ1DIFXGYUvk8QV17wi13o3Lim/Kb3CsEsfYVspso/xq8XtDJDcRw0eOENFsDe9om/8fUj29mCXlZ5iRBhbk1Wnv9sJsn7hDkxhDJKVbMM5l9kMZswdB/Uq7wVkmW5//TSakZ3n10VVLCgH6bOdTi1Ntf7g6AEEiYQJSQGW6oW4QHwvMem19IxN+YTZ3eDk4gKy/UbcAe7325ruuHijRT6+2KFdQTm036JCk5YsyzV02++whuLclvKWoW+594eg9Z3jDviXYDc8HZFUWkhN8/IVwcndkk/EarEtxqOTVg/ipX7WZ/4MJBsbgYullRJ4frvcmtCgoezFnkpjinGUWSXPNeypANMEdUQW0KykM8KYux2girpuCQNccSxBuHbGlKvfVFLHWJys/wZ5XvkrHERHLyM++juURf0jSDBwXoLPK8kIPqJXMt4tnurR6Bf8ZPhFWO0DWBZ9o/DBxsFJrDdQnsIrnTIgAvsG9y7dI0mMMzMywMN6AraYwjYw0Ob+A25TmWPNBAm224ZTPph5cUPZMCltz/iZwkd61fI5RDVpec5g2FRekEEw/YkBI/kR1m5dVg5nzFIm42Af3l+nlPqly92m3RlITf0O/0f0+5DT8Y8H/xrRMKofnpgqwLWASGQ=
  on:
    tags: true
    python: 3.8

env:
  global:
    secure: EkgMWDOUL+HWt6RauzGhxWD7bK1NmhiqgzFqFMZrkMUdfxLkahs1iStBnJktK3UEBfS4fz6LK+wjIpunVdvne+bFCnB3E2LHvHQ7qUwbxsanVWm93kkS6OEY/iE8VJ3JS8g6ATKoP8r957/jzPLuSVgxkQlXlz9zZbTWsSqUMc8b3Pt6XOUTzXnCmNvtMBMDa6PpRC3qVJvaELEzXb4JFD56tYVWDPQTMOMYVe0BV3oADlFu/Rlqr3wb77AeEMmSfzSc8BQ1t+N8GsDHOOknqcXFO5ze5epy7l8FVW+uWni2WoaIttzCoyfWPTA/JgePl4qtOzczJpMDwAROq3jxCQ5PziD33N9KWuKfAWaXXCBf4HzdLetpB0tluFQEvEDS28KBK5JaLXVjnkE8bymjYgBZPxCi6zm5cUh7a6g0GpWhcdsU76PpeeRrsBSTTHilOvjdmN0xN2U8wCDLspGFiIoteho/xRbAL+x1sFzKXE7d2JRrmxWxx69ktmXiTu+/1lxbLSuMQIhOfIIiSUxfjLwdwABJP3RfU+94cGfwqV9HEQBFTxLMg/hG3DPh8Ke4Y6YxUtNEo6I6LlCWnsXgzAP9tUP4osc3snU/AQlIs6pfk0cEzMD54GeSC/DrXbD/02etMbTcvQ9z2C3rhnvQBzwBH5hWF/g51egvU5MDYA0=
