

trigger:
  branches:
    include:
      - master
  tags:
    include:
      - '*'

schedules:
- cron: '0 3 * * 6'
  displayName: "Weekly scheduled build"
  branches:
    include: 
      - 'master'
  always: true

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python38:
      python.version: '3.8'
    Python39:
      python.version: '3.9'
    Python3x:
      python.version: '3.x'
steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install pipenv twine wheel
    pipenv install --system --dev
    pip install .
  displayName: 'Install dependencies'

- script: |
    flake8 nessclient nessclient_tests
  displayName: 'Check Formatting'

- script: |
    mypy --strict nessclient
  displayName: 'Check Types'

- script: |
    coverage run --source=nessclient setup.py test
  displayName: 'Tests (with coverage)'

- script: |
    bash <(curl -s https://codecov.io/bash)
  displayName: 'Upload to codecov.io'

- task: TwineAuthenticate@1
  inputs:
    pythonUploadServiceConnection: 'nessclient'

- script: |
    sed -i '' "s/0.0.0-dev/$(git describe --tags)/" samsungwsctl.py
    python setup.py bdist_wheel
    python -m twine upload -r 'nessclient' --config-file $(PYPIRC_PATH) dist/*.whl
  condition: and(succeeded(), eq(variables['python.version'], '3.9'), startsWith(variables['Build.SourceBranch'], 'refs/tags/'))
  displayName: "Release to PyPi"
